### ISSUE TITLE
Ruby client chokes importing datacenters.csv

### ISSUE THREAD

**Issue by n1zyy** [client9/ipcat#103]
Found a fun little bug with the Ruby client tonight. Some provider names have a comma in them, which breaks the Ruby client:

```
2.2.1 :001 > require './ipcat.rb'
 => true
2.2.1 :002 > dc = IPCat::Datacenters.new('./datacenters.csv')
ArgumentError: wrong number of arguments (5 for 3..4)
	from /Users/mawagner/src/ipcat/ipcat.rb:16:in `add'
	from /Users/mawagner/src/ipcat/ipcat.rb:12:in `block in initialize'
	from /Users/mawagner/src/ipcat/ipcat.rb:11:in `map'
	from /Users/mawagner/src/ipcat/ipcat.rb:11:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /Users/mawagner/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

The CSV is (I presume) valid, but the Ruby client just splits on commas. Trivial PR incoming with a fix.

**Comment by shawnps** [comment]
@n1zyy thanks for reporting this. Taking a look at your PR now.
